import '../models/property_model.dart';

class MockDataService {
  static List<Property> getProperties() {
    return [
      Property(
        id: '1',
        title: 'सुन्दर २BHK फ्ल्याट - लजिम्पाट',
        description:
            'लजिम्पाट को शान्त ठाउँमा राम्रो २BHK फ्ल्याट। सबै सुविधाहरू उपलब्ध छन्। बजार, स्कुल र अस्पतालको नजिक। सार्वजनिक यातायात सजिलै उपलब्ध।',
        address: 'लजिम्पाट, काठमाडौँ',
        city: 'काठमाडौँ',
        district: 'काठमाडौँ',
        price: 25000,
        priceType: 'monthly',
        type: PropertyType.flat,
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 850,
        images: [
          'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        ],
        amenities: ['पार्किङ', 'लिफ्ट', 'सुरक्षा', 'पानी', 'बिजुली'],
        ownerName: 'राम बहादुर श्रेष्ठ',
        ownerPhone: '9841234567',
        ownerImage:
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
        latitude: 27.7172,
        longitude: 85.3240,
        isVerified: true,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 3)),
        furnishingStatus: 'furnished',
      ),
      Property(
        id: '2',
        title: 'आरामदायक कोठा - थमेल',
        description:
            'थमेलको मुटुमा सुन्दर कोठा। वाइफाई र खाना सुविधा सहित। विदेशी र नेपाली दुवैलाई उपयुक्त। रेस्टुरेन्ट र पसलहरूको नजिक।',
        address: 'थमेल, काठमाडौँ',
        city: 'काठमाडौँ',
        district: 'काठमाडौँ',
        price: 12000,
        priceType: 'monthly',
        type: PropertyType.room,
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 300,
        images: [
          'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
          'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
        ],
        amenities: ['वाइफाई', 'पानी', 'बिजुली', 'खाना'],
        ownerName: 'सुनिता तामाङ',
        ownerPhone: '9851234567',
        ownerImage:
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
        latitude: 27.7154,
        longitude: 85.3123,
        isVerified: true,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 1)),
        furnishingStatus: 'furnished',
      ),
      Property(
        id: '3',
        title: 'ठूलो ३BHK घर - बालुवाटार',
        description:
            'बालुवाटारमा विशाल ३BHK घर। ठूलो बगैँचा र छत सहित। शान्त वातावरण। परिवारको लागि उत्तम। गाडी पार्किङ र जेनेरेटर सुविधा।',
        address: 'बालुवाटार, काठमाडौँ',
        city: 'काठमाडौँ',
        district: 'काठमाडौँ',
        price: 55000,
        priceType: 'monthly',
        type: PropertyType.house,
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 1800,
        images: [
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
          'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800',
          'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800',
        ],
        amenities: ['पार्किङ', 'बगैँचा', 'जेनेरेटर', 'सुरक्षा', 'इन्टरनेट'],
        ownerName: 'हरि प्रसाद पौडेल',
        ownerPhone: '9861234567',
        ownerImage:
            'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
        latitude: 27.7250,
        longitude: 85.3200,
        isVerified: true,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 5)),
        furnishingStatus: 'semi-furnished',
      ),
      Property(
        id: '4',
        title: 'मोडर्न अपार्टमेन्ट - जावलाखेल',
        description:
            'ललितपुरको जावलाखेलमा नयाँ मोडर्न अपार्टमेन्ट। उच्च स्तरको फिनिशिङ। स्विमिङ पुल र जिम सुविधा। सुपर मार्केटको नजिक।',
        address: 'जावलाखेल, ललितपुर',
        city: 'ललितपुर',
        district: 'ललितपुर',
        price: 45000,
        priceType: 'monthly',
        type: PropertyType.apartment,
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1100,
        images: [
          'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
          'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
        ],
        amenities: ['स्विमिङ पुल', 'जिम', 'लिफ्ट', 'CCTV', 'पार्किङ'],
        ownerName: 'मीना गुरुङ',
        ownerPhone: '9871234567',
        ownerImage:
            'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
        latitude: 27.6711,
        longitude: 85.3175,
        isVerified: false,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 7)),
        furnishingStatus: 'furnished',
      ),
      Property(
        id: '5',
        title: '१BHK फ्ल्याट - भक्तपुर',
        description:
            'ऐतिहासिक भक्तपुर शहरमा सुन्दर फ्ल्याट। पुरानो शहरको दृश्य। शान्त वातावरण। काठमाडौँ जाने बसको नजिक।',
        address: 'सुर्यविनायक, भक्तपुर',
        city: 'भक्तपुर',
        district: 'भक्तपुर',
        price: 15000,
        priceType: 'monthly',
        type: PropertyType.flat,
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 550,
        images: [
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
        ],
        amenities: ['पानी', 'बिजुली', 'छत'],
        ownerName: 'कृष्ण बहादुर कर्माचार्य',
        ownerPhone: '9811234567',
        ownerImage:
            'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
        latitude: 27.6710,
        longitude: 85.4298,
        isVerified: true,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 10)),
        furnishingStatus: 'unfurnished',
      ),
      Property(
        id: '6',
        title: 'अफिस स्पेस - न्यू बानेश्वर',
        description:
            'न्यू बानेश्वरमा व्यावसायिक अफिस स्पेस। मुख्य सडकको नजिक। रिसेप्शन, बैठक कोठा सहित। आधुनिक सुविधाहरू।',
        address: 'न्यू बानेश्वर, काठमाडौँ',
        city: 'काठमाडौँ',
        district: 'काठमाडौँ',
        price: 35000,
        priceType: 'monthly',
        type: PropertyType.office,
        bedrooms: 0,
        bathrooms: 2,
        areaSqFt: 600,
        images: [
          'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
          'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
        ],
        amenities: ['इन्टरनेट', 'AC', 'पार्किङ', 'लिफ्ट', 'CCTV'],
        ownerName: 'प्रकाश अधिकारी',
        ownerPhone: '9841111111',
        ownerImage:
            'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200',
        latitude: 27.6879,
        longitude: 85.3423,
        isVerified: true,
        isAvailable: true,
        postedDate: DateTime.now().subtract(const Duration(days: 2)),
        furnishingStatus: 'furnished',
      ),
    ];
  }

  static List<String> getNepalDistricts() {
    return [
      'काठमाडौँ',
      'ललितपुर',
      'भक्तपुर',
      'पोखरा',
      'चितवन',
      'बुटवल',
      'हेटौडा',
      'विराटनगर',
      'धरान',
      'इटहरी',
      'जनकपुर',
      'नेपालगन्ज',
      'धनगढी',
      'भरतपुर',
      'बिर्गञ्ज',
    ];
  }

  static List<String> getAmenities() {
    return [
      'पार्किङ',
      'लिफ्ट',
      'सुरक्षा',
      'पानी',
      'बिजुली',
      'वाइफाई',
      'इन्टरनेट',
      'जेनेरेटर',
      'AC',
      'CCTV',
      'जिम',
      'स्विमिङ पुल',
      'बगैँचा',
      'छत',
      'खाना',
    ];
  }
}