// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfn26tJUSiR4StBXoZro6oh-sLIEaj6vU',
    appId: '1:263563030149:web:1c3a39f3c71b5e4c7683ec',
    messagingSenderId: '263563030149',
    projectId: 'gharbhadad',
    authDomain: 'gharbhadad.firebaseapp.com',
    storageBucket: 'gharbhadad.firebasestorage.app',
    measurementId: 'G-02LWKY32VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRN-7XvGu23L411_BjS_45pbX_GWxbzDo',
    appId: '1:263563030149:android:0fe6f4f4d304f0207683ec',
    messagingSenderId: '263563030149',
    projectId: 'gharbhadad',
    storageBucket: 'gharbhadad.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyH3rRWJkd8uVmjpfTHs1BBpH1o1HzDyE',
    appId: '1:263563030149:ios:1102b4b964abe10f7683ec',
    messagingSenderId: '263563030149',
    projectId: 'gharbhadad',
    storageBucket: 'gharbhadad.firebasestorage.app',
    iosBundleId: 'com.example.nepalHomerent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyH3rRWJkd8uVmjpfTHs1BBpH1o1HzDyE',
    appId: '1:263563030149:ios:1102b4b964abe10f7683ec',
    messagingSenderId: '263563030149',
    projectId: 'gharbhadad',
    storageBucket: 'gharbhadad.firebasestorage.app',
    iosBundleId: 'com.example.nepalHomerent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfn26tJUSiR4StBXoZro6oh-sLIEaj6vU',
    appId: '1:263563030149:web:d89881c726f2b9477683ec',
    messagingSenderId: '263563030149',
    projectId: 'gharbhadad',
    authDomain: 'gharbhadad.firebaseapp.com',
    storageBucket: 'gharbhadad.firebasestorage.app',
    measurementId: 'G-64G82M9WD2',
  );
}
